export const NEXT_CHARACTER = 'NEXT_CHARACTER';
export const RECORD_VOICE = 'RECORD_VOICE';
export const RECOGNIZE_VOICE = 'RECOGNIZE_VOICE';
export const UPDATE_VOICE_RECOGNITION_RESULT = 'UPDATE_VOICE_RECOGNITION_RESULT';
export const UPDATE_RECOGNIZER_AUTHORIZATION = 'UPDATE_RECOGNIZER_AUTHORIZATION';