export const NEXT_CHARACTER = 'NEXT_CHARACTER';
export const RECORD_VOICE = 'RECORD_VOICE';
export const RECOGNIZE_VOICE = 'RECOGNIZE_VOICE';
export const UPDATE_VOICE_RECOGNITION_RESULT = 'UPDATE_VOICE_RECOGNITION_RESULT';
export const UPDATE_RECOGNIZER_AUTHORIZATION = 'UPDATE_RECOGNIZER_AUTHORIZATION';
export const START_RECORDER_TIMER = 'START_RECORDER_TIMER';
export const STOP_RECORDER_TIMER = 'STOP_RECORDER_TIMER';
export const UPDATE_RECORDER_TIME = 'UPDATE_RECORDER_TIME';